
#!/bin/bash

# Get the absolute path of the current directory
SCRIPT_DIR=$(pwd)

# Generate the udev rule
UDEV_RULE="# Generated by generate_udev_rule.sh
ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{idVendor}==\"1d50\", ATTR{idProduct}==\"606f\", RUN+=\"/bin/bash -c $SCRIPT_DIR/setcan0_1M.sh\"
"

# Print the generated udev rule
echo "$UDEV_RULE"

# Ask if the user wants to save it to a file
read -p "Do you want to save this rule to a file in /etc/udev/rules.d/? (y/n): " -n 1 REPLY
echo
if [ "$REPLY" = "y" ] || [ "$REPLY" = "Y" ]; then
    # Save it to a file
    echo "$UDEV_RULE" | sudo tee /etc/udev/rules.d/45-usb-can-adapter.rules > /dev/null
    # Reload udev rules
    sudo udevadm control --reload-rules && sudo udevadm trigger
    echo "Udev rule saved and udev rules reloaded."
else
    echo "You can manually save the above rule to /etc/udev/rules.d/45-usb-can-adapter.rules"
fi
