#!/bin/bash

# Copy setcan0_1M.sh to /usr/local/bin
sudo cp setcan0_1M.sh /usr/local/bin/
sudo chmod +x /usr/local/bin/setcan0_1M.sh

# Generate the udev rule
UDEV_RULE="# Generated by setup_udev_rule.sh
ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{idVendor}==\"1d50\", ATTR{idProduct}==\"606f\", RUN+=\"/usr/local/bin/setcan0_1M.sh\"
"

# Save it to a file
echo "$UDEV_RULE" | sudo tee /etc/udev/rules.d/45-usb-can-adapter.rules > /dev/null

# Reload udev rules
sudo udevadm control --reload-rules && sudo udevadm trigger

echo "Udev rule saved and udev rules reloaded."

